### PR TITLE
Added Unit tests

### PR DESCRIPTION
**Pull request by Boscillator**
Here are some not particularity useful unit tests, but they're a start.

### CODE REVIEW

**Comment by evhub** [comment]
@Boscillator Right now, all of Coconut's tests exist in the separate [cocotest](https://github.com/evhub/cocotest) repository. I'm not sure how I feel about adding unit tests to the main repository. Either way, if we're adding a new test system, we'll have to modify [coconut-travis-generator](https://github.com/evhub/coconut-travis-generator) which generates the `.travis.yml` files for both repositories (these files describe what test commands Travis should run).

**Comment by Boscillator** [comment]
Oh, I didn't know that existed, you should probably link to it from the read me or something.

**Comment by evhub** [comment]
@Boscillator I agree that unit testing would be nice, since right now `cocotest` is mostly just integration testing. I do think I'd like to put the unit tests in the `cocotest` repository, though, which will also require a modification to `coconut-travis-generator` to make it call them.

**Comment by Boscillator** [comment]
Ok, I'll clone the `cocotest` repo and put these files in it. Then I'll see about the generator.

**Pull request closed without merging**
