### PR TITLE
updated README for open collective

### PR DESCRIPTION
**Pull request by monkeywithacupcake**
Hi, I'm making updates for Open Collective. Either you or a supporter signed this repo up for Open Collective. This pull request adds backers and sponsors from your Open Collective https://opencollective.com/coconut❤️

It adds two badges at the top to show the latest number of backers and sponsors. It also adds placeholders so that the avatar/logo of new backers/sponsors can automatically be shown without having to update your README.md. [more info](https://github.com/opencollective/opencollective/wiki/Github-banner). See how it looks on this [repo](https://github.com/apex/apex#backers).

You can also add a postinstall script to let people know after npm|yarn install that you are welcoming donations (optional). [More info](https://github.com/OpenCollective/opencollective-cli)
You can also add a "Donate" button to your website and automatically show your backers and sponsors there with our widgets. Have a look here: https://opencollective.com/widgets

P.S: As with any pull request, feel free to comment or suggest changes. The only thing "required" are the placeholders on the README because we believe it's important to acknowledge the people in your community that are contributing (financially or with code!).

Thank you for your great contribution to the open source community. You are awesome! 🙌
And welcome to the open collective community! 😊

Come chat with us in the #opensource channel on https://slack.opencollective.com - great place to ask questions and share best practices with other open source sustainers!

### CODE REVIEW

**Comment by evhub** [comment]
@monkeywithacupcake Coconut's README is written in RST, not Markdown, so this PR is getting closed as invalid, and whoever's responsible for writing this bot should probably be checking README file extensions.

**Comment by monkeywithacupcake** [comment]
Sorry, I tried. I edited the .rst perhaps I did not do it correctly . I did paste our typical blurb in about the edits, which are usually in markdown. I hope that you can use the suggested edits to make it easy for your users to donate to your Open Collective and be recognized. Thanks for your contribution to open source.

**Comment by evhub** [comment]
@monkeywithacupcake I went ahead and rewrote your standard Markdown in RST instead, which you can find [here](https://github.com/evhub/coconut/blob/develop/README.rst) ([source](https://raw.githubusercontent.com/evhub/coconut/develop/README.rst). That code is now part of Coconut, which is licensed under Apache 2.0, so you're welcome to take it and use it if you ever run into another RST readme in the future.

**Comment by monkeywithacupcake** [comment]
Thank you so much! I get a little dizzy looking through so many READMEs, and I do make mistakes!

**Pull request closed without merging**
