### PR TITLE
Fix TLS error

### PR DESCRIPTION
**Pull request by raxod502**
Adding a CNAME file for GitHub Pages should fix the cert name error:

image

### CODE REVIEW

**Comment by evhub** [comment]
Thanks Radon! It's not letting me automatically merge it into the `gh-pages` branch, but I'll just copy it over.

**Comment by evhub** [comment]
Hmmm... actually, now that I'm looking at the [`CNAME` already on the `gh-pages` branch](https://github.com/evhub/coconut/blob/gh-pages/CNAME), it looks like it already has the right domains in in it, so I'm not sure what's causing this.

**Comment by evhub** [comment]
I think the error was being caused by the DNS pointing to old GitHub pages IP addresses—hopefully it'll be fixed now once the changes I just made propagate.

**Comment by raxod502** [comment]
Huh, for some reason it still seems to be erroring:

```
% http https://coconut-lang.org

http: error: SSLError: HTTPSConnectionPool(host='coconut-lang.org', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError("hostname 'coconut-lang.org' doesn't match either of 'www.github.com', '*.github.com', 'github.com', '*.github.io', 'github.io', '*.githubusercontent.com', 'githubusercontent.com'"))) while doing GET request to URL: https://coconut-lang.org/
```

**Comment by evhub** [comment]
Frustrating. I just [tried a change to the `CNAME` file](https://github.com/evhub/coconut/commit/52fe74188478c5ee7cca59f85cb5ab917df4a291), we'll see if that fixes it.

**Comment by raxod502** [comment]
Moved to https://github.com/evhub/coconut/issues/590 for better tracking.

**Pull request closed without merging**
