### PR TITLE
Add check in @addpattern whether the function is pattern-matching

### LINKED ISSUE #496: Handle addpattern on a non-pattern-matching function in a useful way
Currently, if you have an ordinary function and you either use `@addpattern` or the `addpattern def` keyword on it, it doesn't actually yield any useful result:

```python
def f(n) = [n]
addpattern def f(n, m) = [n,m] # Attempting to call f with two arguments will intead throw an error.
```

Of course, one can use the `match def` keyword to tell Coconut this is a pattern-matching function, however, it's quite easy to forget to add it, especially when the function was originally defined without a second pattern for it in mind. The `addpattern` decorator should be able to detect that `f` is not already a pattern-matching function, and either:
 - Convert `f` to a pattern-matching function, allowing you to elide the `match` keyword altogether,
 - Or, if that's not actually possible for some reason, at least emit a warning/error that immediately clarifies the issue (*addpattern should not be used with non-pattern-matching functions!*) instead of a less obvious error about a wrong number of arguments that doesn't reveal the underying issue later down the line.

### PR DESCRIPTION
**Pull request by m-burst**
Compiler now emits a statement which sets `_coconut_is_pattern_matching` flag on pattern-matching functions.  This flag is checked in `@addpattern`, which emits a `UserWarning` if it encounters a function for which the flag is missing.

Fixes #496.

### CODE REVIEW

**Comment by m-burst** [comment]
Turns out this doesn't work on Python 2, because `functools.wraps` doesn't set the `__wrapped__` attribute there. I'll take a closer look on what can be done here.

**Comment by m-burst** [comment]
Rewrote this to a flag-based solution, as originally suggested in the issue.

I still have a few questions about this change though:
1. The way to determine pattern-matching functions by signature feels a little bit hacky to me. Maybe there is a better solution that I'm not seeing?
2. In the test suite there are a few `@addpattern`s on non-pattern-matching functions which emit warnings during tests, and these warnings currently fail the test suite because of the output checking.  How should I deal with these? Should I convert these functions in tests to pattern-matching, or should I silence the warning in these places?

@evhub Please take a look at the code and at my questions above. Thanks in advance!

**Comment by m-burst** [comment]
Hi @evhub, could you please give your feedback on this?

**Comment by evhub** [comment]
@m-burst Looks good, though could you add some tests for this?

**Pull request merged**
