### PR TITLE
File watcher

### PR DESCRIPTION
**Pull request by Boscillator**
Added file and directory watching flag. This is as requested in issue #99.
Usage:
```
coconut --watch examples/example.coco
coconut --watch examples
```

I did not use the watchdogs library because I wanted to keep dependencies minimal.

### CODE REVIEW

**Comment by evhub** [comment]
Looks good--just a couple of things that either you can fix now or I will fix when I merge it:

- Should never have a `while True` loop without some sort of `time.sleep` call to prevent it from taking up too much CPU time.
- Your watch function can't just call plain `compile_path(source)`, it needs to respect all of the other arguments that might have been passed, thus I would make the call to `watch` replace the call to `compile_path` in `if args.source is not None:` such that `watch` takes all the same arguments, and then passes them along to `compile_path` when it calls it.

**Comment by Boscillator** [comment]
Ok, I'll work on it.

**Comment by candeira** [comment]
Watching files by looping and looking at times is far from good practice, especially when there exist libraries that hook into the host OS and provide you with callbacks when files change:

I use gamin: 
- https://people.gnome.org/~veillard/gamin/python.html
But there are other more recent entrants like watchdog:
- https://github.com/gorakhargosh/watchdog

**Comment by Boscillator** [comment]
I was trying to keep dependencies to a minimum, but I'll look into it.

**Comment by evhub** [comment]
I think introducing more required dependencies is not a good idea, but if you just put the import statement inside of the `watch` function, then Coconut remains usable by anyone who doesn't have the dependency and best practices can still be maintained.

**Comment by Boscillator** [comment]
Ok, so the problem with that is watchdogs wants me to subclass on of their classes. This would mean I would need to declare the class in the `watch` function, which would be ugly.
The other option would be to create a `watch.py` file, containing the watch function and the class and watchdogs imported at the top, and only import that the watch function needs to be called.
Does that seam like a good plan.

**Comment by Boscillator** [comment]
Ok, it now uses watchdogs.

**Comment by evhub** [comment]
Looks good! I'll try to merge it soon.

**Pull request merged**
